/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Koneksi.KoneksiDB;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.font.PDFont;
import org.apache.pdfbox.pdmodel.font.PDType1Font;

/**
 *
 * @author User
 */
public class CetakAntrian extends javax.swing.JFrame {

    /**
     * Creates new form CetakAntrian
     */
    public CetakAntrian() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomor_antrian = new javax.swing.JTextField();
        lihat = new javax.swing.JButton();
        cetak = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("CETAK ANTRIAN");

        jLabel2.setText("Nomor Antrian");

        lihat.setText("Lihat");
        lihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatActionPerformed(evt);
            }
        });

        cetak.setText("Cetak");
        cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakActionPerformed(evt);
            }
        });

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Pasien", "NIK", "Klinik", "Dokter", "Spesialisl", "Tanggal"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(171, 171, 171))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(nomor_antrian, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lihat, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cetak, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomor_antrian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lihat)
                    .addComponent(cetak))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatActionPerformed
        // TODO add your handling code here:
        int IdAntrian = Integer.parseInt(nomor_antrian.getText());
        try{
            Connection kon = KoneksiDB.getKoneksi();
            Statement stat = kon.createStatement();

            String sqlCari = "SELECT * FROM mendaftar INNER JOIN tb_pasien ON mendaftar.nik = tb_pasien.nik INNER JOIN antrian ON mendaftar.id_antrian = antrian.id_antrian INNER JOIN antrian ON tb_klinik.id_klinik = antrian.id_klinik INNER JOIN antrian ON tb_dokter.nama_dokter = antrian.nama_dokter WHERE antrian.id_antrian = \"+IdAntrian+";
            ResultSet r = stat.executeQuery(sqlCari);

            while(r.next()){
                String _namapasien = r.getString("tb_pasien.nama_lengkap");
                String _nik = r.getString("tb_pasien.nik");
                String _antrian = r.getString("antrian.id_antrian");
                String _namaklinik = r.getString("tb_klinik.nama_klinik");
                String _namadokter = r.getString("tb_dokter.nama_dokter");
                String tanggal = r.getString("antrian.waktu").substring(0, 10);

                DefaultTableModel model = (DefaultTableModel)tabel.getModel();

                Object []  dataYangDitampil = {_namapasien, _nik, _antrian, _namaklinik, _namadokter, tanggal};
                model.addRow(dataYangDitampil);

            }
            r.close();
            stat.close();

        } catch (SQLException e) {
            String pesan = "Terjadi Lesalahan Dalam Menampilkan Antrian";
            JOptionPane.showMessageDialog(null, pesan + e.getMessage());
        }
    }//GEN-LAST:event_lihatActionPerformed

    private void cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakActionPerformed
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_cetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CetakAntrian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CetakAntrian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CetakAntrian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CetakAntrian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CetakAntrian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cetak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lihat;
    private javax.swing.JTextField nomor_antrian;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables

    private void CetakTiketPDF(String _namapasien, String _nik, String _antrian, String _namaklinik, String _namadokter, String tanggal) {
        //Deklarasi halaman pdf baru
        PDPage Antrian = new PDPage();
        //pilih jenis dan ukuran font yang ingin dipakai
        PDFont JenisFont = PDType1Font.COURIER;
        int fontSize = 12;
        //Buat file pdf
        try (PDDocument dokumen = new PDDocument()) {
        //Buat halaman baru
        dokumen.addPage(Antrian);
        //Buat objek content yang akan diisi teks
        PDPageContentStream content= new PDPageContentStream(dokumen, Antrian);
        //Mulai menulis dokumen
        content.beginText();
        //Aktifkan font yang telah dipilih di awal
        content.setFont(JenisFont, fontSize);
        //Atur besarnya spasi antar baris
        content.setLeading(20f);
        //Atur posisi awal penulisan teks 

        content.newLineAtOffset(50, 750);
        //Menulis isi dokumen
        content.showText("Antrian Pasien");
        content.newLine();
        content.newLine(); //dua kali enter
        content.showText("Nama Pasien: " + _namapasien);
        content.newLine(); //pindah baris
        content.showText("NIK Pasien : " + _nik);
        content.newLine();
        content.showText("Antrian : " + _antrian);
        content.newLine();
        content.showText("Klinik : " + _namaklinik);
        content.newLine();
        content.showText("Dokter : " + _namadokter);
        content.newLine();
        content.showText("Tanggal : " + tanggal );
        //Mengakhiri penulisan dokumen
        content.endText();
        //Menutup dokumen
        content.close(); // Stream must be closed before saving document.
        //Menyimpan dokumen pada direktori tertentu
        dokumen.save("D:/DOCUMENTS/TiketKereta-01.pdf");
        } catch (IOException ioEx) {
        System.out.println("Gagal membuat pdf");
        }
    //Buka file pdf
    try {
        File file = new File("D:/DOCUMENTS/ANTRIAN-001.pdf");
        if (file.exists()) {
            Desktop.getDesktop().open(file);
        } else {
            System.out.println("File not exits -> " + file.getAbsolutePath());
        }
    } catch (IOException e) {
        System.out.println("Gagal membuka file pdf.");

    }}
}
